print("quotes said:\n"
      "He said \"I'm learning Python\" and it\'s fun!\n"
      "file path test:\n"
      "C:\\users\\laksh\\documents\\pythonescapr_demo.py\n"
      "new linw and tab test:\n"
      "name:\n"
      "\tlaksh\n"
      "age:\n"
       "\t25\n"
       "place:\n"
       "\tchennai\n"
       "Backspace and Carriage return test:\n"
       "hello\rworld!\n"
       "hello \b world\n"
       "python rocks!\n"
       "python\rRocks\n"
       "form feed test(may show FF or space depending on terminal)\n"
       "hello\fworld\n"
       "hello \b world"
      )